logdir: models/stage1/effb1-f0/
gpus: [0]

# define model
model:
  architecture: Unet
  init_params:
    encoder_name: efficientnet-b1
    encoder_weights: imagenet
    classes: 1
    activation: sigmoid

data:

  df_path: ./data/train_0/folds.csv
  fold: 0

  # datasets
  train_dataset:
    name: SegmentationDatasetEye
    init_params:
      images_dir: ./data/train_0/images/
      masks_dir: ./data/train_0/masks/
      transform_name: train_transform_4

  valid_dataset:
    name: SegmentationDatasetEye
    init_params:
      images_dir: ./data/train_0/images/
      masks_dir: ./data/train_0/masks/
      transform_name: test_transform_4

  # loaders
  train_dataloader:
    batch_size: 4
    shuffle: true
    drop_last: true
    pin_memory: true
    num_workers: 8

  valid_dataloader:
    batch_size: 4
    shuffle: false
    drop_last: false
    pin_memory: true
    num_workers: 16

training:

  losses:
    mask:
      name: DiceLoss
      init_params:

  metrics:
    mask:
      - name: MicroIoU
        init_params:

  optimizer:
    name: Adam
    init_params:
      lr: 0.0001

  scheduler:
    name: PolyLR
    init_params:
      epochs: 50

  fit:
    epochs: 50
    accumulation_steps: 6
    verbose: true

  callbacks: []
